name: CI

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '**/*.md'
      - '**/.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
  push:
    branches: [develop]
    paths-ignore:
      - '**/*.md'
      - '**/.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
          gradle-home-cache-cleanup: true

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build (lint + tests + APK)
        run: |
          ./gradlew \
            lintDebug \
            testDebugUnitTest \
            assembleDebug \
            -Dorg.gradle.caching=true \
            -Dorg.gradle.configuration-cache=true \
            --parallel \
            --build-cache \
            --stacktrace

      - name: Upload debug APK
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          retention-days: 3

      - name: Upload unit test reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/**
            **/build/test-results/**
          retention-days: 7

      - name: Upload lint report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            **/build/reports/lint-results*.html
            **/build/reports/lint-results*/*.html
          retention-days: 7

