name: Release Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Run tests
        run: ./gradlew test

      - name: Build and Sign Release APK
        id: sign_apk
        run: |
          if [[ -n "${{ secrets.KEYSTORE_FILE }}" ]]; then
            echo "Signing APK..."
            echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks
            KEYPATH="$GITHUB_WORKSPACE/app/keystore.jks"
            ./gradlew assembleRelease \
              -Pandroid.injected.signing.store.file=$KEYPATH \
              -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
              -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
              -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"
            echo "SIGNED=true" >> $GITHUB_OUTPUT
          else
            echo "Signing secrets not found, building unsigned APK..."
            ./gradlew assembleRelease
            echo "SIGNED=false" >> $GITHUB_OUTPUT
          fi

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release*.apk app/build/outputs/apk/release/waiotech-v${{ steps.get_version.outputs.VERSION }}.apk

      - name: Create GitHub Release & upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }} # e.g. v1.2.3
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          body: |
            ## What's Changed

            Release version ${{ steps.get_version.outputs.VERSION }}

            ### Installation
            Download the APK file below and install it on your Android device.

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.get_version.outputs.VERSION }}...HEAD
          artifacts: app/build/outputs/apk/release/app-v${{ steps.get_version.outputs.VERSION }}.apk
          artifactContentType: application/vnd.android.package-archive
          token: ${{ github.token }}
